parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                url: '%env(DATABASE_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
            # default_table_options:
            #    charset: utf8mb4
            #   collate: utf8mb4_unicode_ci
            calendar_connection:
                # configure these for your database server
                url: '%env(DATABASE_CALENDAR_URL)%'
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8mb4
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/RoEntity'
                        prefix: 'App\Entity\RoEntity'
                        alias: Main
            calendar_manager:
                connection: calendar_connection
                naming_strategy: doctrine.orm.naming_strategy.underscore
                mappings:
                    Calendar:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/CalendarEntity'
                        prefix: 'App\Entity\CalendarEntity'
                        alias: Calendar
